version: "3.8"

services:
  subco:
    build: .
    container_name: subco-mqtt-client
    restart: unless-stopped
    depends_on:
      - mqtt-broker
    environment:
      - NODE_ENV=production
    networks:
      - mqtt-network
    # Uncomment if you need to access logs
    # volumes:
    #   - ./logs:/usr/src/app/logs

  # MQTT Broker (Eclipse Mosquitto)
  # Remove this service if you're using an external MQTT broker
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-logs:
